# Generated by Django 4.2 on 2023-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=100)),
                ('sanskrit_name_adapted', models.CharField(blank=True, max_length=100)),
                ('sanskrit_name', models.CharField(blank=True, max_length=100)),
                ('translation_name', models.CharField(blank=True, max_length=100)),
                ('pose_benefits', models.TextField(blank=True)),
                ('url_svg', models.URLField(blank=True)),
                ('url_png', models.URLField(blank=True)),
                ('url_svg_alt', models.URLField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField(blank=True)),
                ('poses', models.ManyToManyField(related_name='categories', to='yogit.pose')),
            ],
        ),
    ]
