# Generated by Django 4.2 on 2023-04-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='api_id',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pose',
            name='api_id',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
