# Generated by Django 4.2 on 2023-04-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogit', '0003_rename_category_description_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20),
        ),
    ]
