# Generated by Django 4.2 on 2023-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogit', '0004_alter_pose_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pose',
            name='pose_description',
            field=models.TextField(blank=True),
        ),
    ]
