# Generated by Django 4.2 on 2023-04-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogit', '0005_pose_pose_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pose',
            name='yoga_category',
        ),
        migrations.AddField(
            model_name='pose',
            name='yoga_categories',
            field=models.ManyToManyField(to='yogit.category'),
        ),
    ]
