# Generated by Django 4.2 on 2023-05-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogit', '0006_remove_pose_yoga_category_pose_yoga_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PoseType',
        ),
        migrations.RenameField(
            model_name='pose',
            old_name='yoga_categories',
            new_name='type',
        ),
    ]
