# Generated by Django 4.2 on 2023-05-10 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yogit', '0007_rename_category_posetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedPose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yogit.pose')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
