# Generated by Django 4.2.1 on 2023-05-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogit", "0008_usersavedpose"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pose",
            name="api_id",
        ),
        migrations.RemoveField(
            model_name="posetype",
            name="api_id",
        ),
        migrations.AlterField(
            model_name="pose",
            name="id",
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="posetype",
            name="id",
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
