# Generated by Django 4.2.1 on 2023-06-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yogit", "0010_usersequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersequence",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
