# Generated by Django 4.2.1 on 2023-06-08 15:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yogit", "0012_sequencepose_alter_usersequence_poses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersequence",
            name="poses",
        ),
    ]
